token-config: &token-config
  key: xy-token

hash: &hash
  hash_type: sha256
  salt: ray-sso
  iterations: 9


environment-product:
  token-config:
    <<: *token-config
  hash:
    <<: *hash


environment-development:
  token-config:
    <<: *token-config
  hash:
    <<: *hash


environment-test:
  token-config:
    <<: *token-config
  hash:
    <<: *hash

