flask: &flask
  host: 0.0.0.0
  port: 3399
  threaded: true
  debug: true

flask-config: &flask-config
  SECRET_KEY: ray-iam
  PERMANENT_SESSION_LIFETIME:
    days: 1

cookie-config: &cookie-config
  key: xy-auth
  max_age: 86400
  domain: null
  secure: false
  httponly: true

token-config: &token-config
  key: xy-token

hash: &hash
  hash_type: sha256
  salt: ray-iam
  iterations: 9

database: &database
  scheme: mysql+pymysql
  user: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  db: ray_iam
  charset: utf8mb4

cache: &cache
  serialize: pickle
  redis: &redis
    password: null
    host: 127.0.0.1
    port: 6379
    auth-db:
      db: 9
      ex: 86400
    we-chat-db:
      db: 10
      ex: 86400
  mongodb: &mongodb
    host: 127.0.0.1
    port: 27017

ssl: &ssl
  private_key: 2_ray3175.cn.key
  public_key: 1_ray3175.cn_bundle.crt

we_chat: &we_chat
  appid: wxa1bf05b0e7da32e2
  secret: 0b107c9b82e5796c6b69caea73ba1939
  api:
    code2Session:
      url: https://api.weixin.qq.com/sns/jscode2session
      grant_type: authorization_code


environment-product:
  flask:
    debug: false
    <<: *flask
  flask-config:
    SECRET_KEY: ray-iam
    <<: *flask-config
  cookie-config:
    <<: *cookie-config
  token-config:
    <<: *token-config
  hash:
    <<: *hash
  database:
    scheme: mysql+pymysql
    user: root
    password: 123456
    host: 127.0.0.1
    port: 3306
    <<: *database
  cache:
    redis:
      password: null
      host: 127.0.0.1
      port: 6379
      <<: *redis
    mongodb:
      host: 127.0.0.1
      port: 27017
      <<: *mongodb
    <<: *cache
  ssl:
    <<: *ssl
  we_chat:
    <<: *we_chat

environment-development:
  flask:
    <<: *flask
  flask-config:
    <<: *flask-config
  cookie-config:
    <<: *cookie-config
  token-config:
    <<: *token-config
  hash:
    <<: *hash
  database:
    <<: *database
  cache:
    <<: *cache
  ssl:
    <<: *ssl
  we_chat:
    <<: *we_chat

environment-test:
  flask:
    debug: false
    <<: *flask
  flask-config:
    <<: *flask-config
  cookie-config:
    <<: *cookie-config
  token-config:
    <<: *token-config
  hash:
    <<: *hash
  database:
    scheme: mysql+pymysql
    user: root
    password: 123456
    host: 127.0.0.1
    port: 3306
    <<: *database
  cache:
    redis:
      host: 127.0.0.1
      port: 6379
      <<: *redis
    mongodb:
      host: 127.0.0.1
      port: 27017
      <<: *mongodb
    <<: *cache
  ssl:
    <<: *ssl
  we_chat:
    <<: *we_chat

