token-config: &token-config
  key: xy-token

hash: &hash
  hash_type: sha256
  salt: ray-iam
  iterations: 9

ssl: &ssl
  private_key: 2_ray3175.cn.key
  public_key: 1_ray3175.cn_bundle.crt


environment-product:
  token-config:
    <<: *token-config
  hash:
    <<: *hash
  ssl:
    <<: *ssl


environment-development:
  token-config:
    <<: *token-config
  hash:
    <<: *hash
  ssl:
    <<: *ssl


environment-test:
  token-config:
    <<: *token-config
  hash:
    <<: *hash
  ssl:
    <<: *ssl

